baseURL: "https://themayurkumbhar.github.io"
title: themayurkumbhar
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Mayur Kumbhar
  description: "Enthusiastic Technology explorer! Love's Biking 🏍️, Hiking 🏔️ & Eating Delicious Food 😋!"
  keywords: [Blog, Portfolio, PaperMod]
  author: Me
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "themayurkumbhar"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Mayur Kumbhar
    subtitle: "Enthusiastic Technology explorer! 
    
    
    Love's Biking 🏍️, Hiking 🏔️ & Eating Delicious Food 😋!"
    imageUrl: "https://www.gravatar.com/avatar/c31c460353b0acb96692d356aea28965?s=500"
    imageWidth: 240
    imageHeight: 240
    imageTitle: Mayur's Cool Avatar
    buttons:
      - name: Blogs
        url: post
      - name: Tags
        url: tags



  socialIcons:
    - name: email
      url: "mailto:mayur.kumbhar@outlook.com"
    - name: linkedin
      url: "https://www.linkedin.com/in/mayurkumbhar"
    - name: github
      url: "https://github.com/themayurkumbhar"
    - name: dev
      url: "https://dev.to/themayurkumbhar"
    - name: twitter
      url: "https://twitter.com/themayurkumbhar"
    - name: instagram
      url: "https://instagram.com/themayurkumbhar"

#  analytics:
#    google:
#      SiteVerificationTag: "XYZabc"
#    bing:
#      SiteVerificationTag: "XYZabc"
#    yandex:
#      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

#update this url
  editPost:
    URL: "https://github.com/themayurkumbhar/portfolio-hugo-pepermod-base/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content", "tags"]
menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30
    - identifier: search
      name: Search
      url: /search/
      weight: 40

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary


# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    guessSyntax: true
    #lineNos: true
    style: monokai